name: Run Cypress Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        id: cypress
        run: npx cypress run

      - name: Check for Cypress artifacts
        id: check-artifacts
        run: |
          echo "videos-exist=$(if [ -d cypress/videos ]; then echo true; else echo false; fi)" >> $GITHUB_ENV
          echo "screenshots-exist=$(if [ -d cypress/screenshots ]; then echo true; else echo false; fi)" >> $GITHUB_ENV

      - name: Upload Cypress videos
        if: always() && env.videos-exist == 'true'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress screenshots
        if: always() && env.screenshots-exist == 'true'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: cypress-screenshots
          path: cypress/screenshots